# Generated by Django 5.0.1 on 2024-02-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exercisesession_options_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id']},
        ),
    ]
